Добавлено stylelint правило "selector-class-pattern"
core-ds/arui-presets-lint pull request #14
Opened 2024-08-14 15:40 UTC by denisx

Добавлено stylelint правило "selector-class-pattern"

## Мотивация и контекст

Наличие дефиса в классах:
1. Увеличивает размер файла в распакованном виде
2. При создании алиасов в js, требует дополнительные кавычки

Не критично для резких исправлений, но при должном упорстве подсушивает вес сборки.

2024-08-14 15:59 UTC, dmitrbrvsk commented
@denisx привет
могу ошибаться, но кажется что такое правило нужно обсудить и принять на уровне стандартов, а потом только добавлять его

2024-08-14 16:01 UTC, denisx commented
> @denisx привет могу ошибаться, но кажется что такое правило нужно обсудить и принять на уровне стандартов, а потом только добавлять его

всё верно. а ссылка на пр уже готова )

2024-08-14 17:05 UTC, alterfo requested changes

2024-08-14 17:05 UTC, alterfo commented on test/css-input.css
> +.superStyle {
```suggestion
.super_style {
```

2024-08-14 17:38 UTC, heymdall-legal commented
Я бы ограничил приминимость этого правила только css модулями. Достаточно много кода написано на бэме, и никто его переписывать не хочет. И там вариант с дефисами - логичный.
Не уверен сходу можно ли правила применять только для определенных типов файлов правда. Если нет - то правило создаст как по мне больше недовольства от разработчиков чем профита какого то

2024-08-15 07:42 UTC, denisx commented
бэм это проблемка, да

2024-08-15 07:51 UTC, denisx commented
если в команде придерживаются правил именования файлов. в любом случае, переопределить можно в любую сторону на своей строне

2024-08-15 07:57 UTC, heymdall-legal commented
а тут уже вопрос про то, как выбирать дефолты и кто чем пользуется.
Если смотреть на то, как настроена сборка в arui-scripts - css модули будут называться именно `*.module.css`. Понятное дело что есть еще много тех, кто использует другие варианты сборщиков + тех, кто использует оверрайды в самих скриптах, но честно - я вообще не понимаю какой процент проектов живет с такими вариациями

2024-08-15 11:31 UTC, KalashnikovTV commented on stylelint/index.js
> +            files: ['*.module.css'],
Вроде я где-то видел проекты, которые на module scss

2024-08-16 07:08 UTC, heymdall-legal approved these changes

2024-08-16 07:48 UTC, kiskv approved these changes

2024-08-16 07:50 UTC, reabiliti approved these changes

2024-08-16 08:07 UTC, denisx commented on stylelint/index.js
> +            files: ['*.module.css'],
как минимум те, кто работает на аруи ) это точно 50%+ по количеству

2024-08-16 08:09 UTC, denisx commented
@alterfo @KalashnikovTV дайте "пять" и поедем уже =)

2024-08-16 09:35 UTC, KalashnikovTV approved these changes

2024-08-16 11:11 UTC, KalashnikovTV commented on stylelint/index.js
> +            files: ['*.module.css'],
может стоит тогда добавить и для *.module.scss ?

2024-08-16 11:16 UTC, denisx commented on stylelint/index.js
> +            files: ['*.module.css'],
и `less` тоже добавим?

2024-08-16 13:16 UTC, denisx commented on stylelint/index.js
> +            files: ['*.module.css'],
я бы пока ограничился таким правилом по стандартным файлам

2024-08-19 08:25 UTC, KalashnikovTV commented on stylelint/index.js
> +            files: ['*.module.css'],
как знаешь) окей

2024-08-19 09:02 UTC, merged