WIP: feat(*): add stylelint order
core-ds/arui-presets-lint pull request #22
Opened 2024-09-25 21:43 UTC by dmitrbrvsk

## Мотивация и контекст

2024-10-01 12:58 UTC, kiskv commented on package.json
> +        "stylelint-config-prettier": "*",
это не нужно с 15 версии stylelint если что

2025-01-19 15:18 UTC, alterfo approved these changes, later dismissed

2025-01-19 15:18 UTC, alterfo commented on stylelint/index.js
> +        'order/properties-order': ['position', 'z-index', 'top', 'right', 'bottom', 'left'],
для доки:

1. Правило properties-order:
   - Конфигурация 'position', 'z-index', 'top', 'right', 'bottom', 'left' определяет порядок свойств в CSS-правилах, которые описывают позиционирование элементов. Это правило гарантирует, что все эти свойства появляются в этом порядке внутри каждого CSS-правила.

2. Правило order/order:
   - Конфигурация определяет порядок различных типов объявлений (declarations) и at-rules в CSS:
     - 'declarations' указывает на то, что все объявления должны быть первыми.
     - { type: 'at-rule', name: 'media' } означает, что at-rule @media должен следовать за всеми объявлениями.
     - Остальные конфигурации определяют порядок различных типов CSS-селекторов и at-rules:
       - '^&::(before|after)': селекторы, начинающиеся с &::before или &::after.
       - '^&:\w': селекторы, начинающиеся с &:.
       - '^&_': псевдоклассы и атрибутные селекторы.
       - '^.': классовые селекторы.

Таким образом, эти правила помогают поддерживать консистентность в структуре CSS-кода, обеспечивая определенный порядок для различных элементов и объявлений.

2025-02-17 12:49 UTC, denisx commented
на сайте наследуется из `stylelint-config-idiomatic-order`

2025-02-18 09:08 UTC, kiskv requested changes

2025-02-18 09:12 UTC, kiskv commented
А autofix работает кстати?

2025-02-18 12:16 UTC, denisx commented
> на сайте наследуется из `stylelint-config-idiomatic-order`

я к тому, чтобы посмотреть/сравнить что внутри. может более правильная сортировка или ещё что

2025-03-13 14:24 UTC, dmitrbrvsk commented on package.json
> +        "stylelint-config-prettier": "*",
поправил

2025-03-13 14:24 UTC, dmitrbrvsk commented on package.json
> +        "stylelint-config-prettier": "9.0.5",
поправил

2025-03-13 14:25 UTC, dmitrbrvsk commented on package.json
> +        "stylelint-prettier": "5.0.2"
поправил

2025-03-14 11:17 UTC, kiskv approved these changes

2025-03-18 08:00 UTC, qrik116 approved these changes, later dismissed

2026-02-10 09:40 UTC, kiskv requested changes

2026-04-14 06:56 UTC, qrik116 approved these changes

2026-05-05 14:07 UTC, closed without merging

2026-05-05 14:07 UTC, kiskv commented
Долго висит и требует доработок. Пока закрываю