chore(*): add codeowners
core-ds/arui-presets-lint pull request #23
Opened 2024-10-02 14:22 UTC by heymdall-legal

## Мотивация и контекст

Добавляем кодоунеров из числа лидов для обязательных ревью.

Механизмы обновления этого списка, а так же то, какие правила для мержа настроить в этом репозитории обсудим отдельно

2024-10-02 17:08 UTC, kiskv requested changes
в папке .github уже лежит этот файл, он не подходит?

2024-10-09 07:54 UTC, heymdall-legal commented
> в папке .github уже лежит этот файл, он не подходит?

Слепой, не увидел его

2024-10-09 08:31 UTC, qrik116 approved these changes

2024-10-09 09:34 UTC, kiskv approved these changes

2024-10-10 11:44 UTC, merged